defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .

## User Setting ##
root: inputs/images/sample/スギ/Sugi_test
model_path: inputs/models/convnext_small.in12k_ft_in1k_384-augmix-mixup.ckpt
label_map_path: inputs/json/label_map.json
output_dir: outputs
target: 2

## Model ##
model_name: convnext_small.in12k_ft_in1k_384
num_classes: 5

## Transform ##
image_size: 224

## Visualization ##
# https://captum.ai/api/utilities.html#captum.attr.visualization.visualize_image_attr
vis_img:
  enable: True
  method: blended_heat_map
  sign: positive
  plt_fig_axis:
  outlier_perc: 2
  cmap:
  alpha_overlay: 0.5
  show_colorbar: False
  fig_size: [6, 6]
  use_pyplot: True

# https://captum.ai/api/utilities.html#captum.attr.visualization.visualize_image_attr_multiple
vis_img_multi:
  enable: True
  methods: ["heat_map", "original_image"]
  signs: ["positive", "all"]
  outlier_perc: 2
  cmap:
  alpha_overlay:
  show_colorbar: True
  fig_size: [6, 6]
  use_pyplot: True

## Algorithm ##

# Guided Grad-CAM
# https://captum.ai/api/guided_grad_cam.html#captum.attr.GuidedGradCam
# !!! When using Guided Grad-CAM, you must specify a layer (line 27 in guided_gc.py).
ggc:
  device_ids:
  additional_forward_args:
  interpolate_mode: nearest
  attribute_to_layer_input: False

gradcam:
  device_ids:
  additional_forward_args:
  attribute_to_layer_input: False
  relu_attributions: True

# Saliency
# https://captum.ai/api/saliency.html#captum.attr.Saliency
saliency:
  abs: False
  additional_forward_args:
